version: "3"
services:
  oracle11g:
    image: jaspeen/oracle-xe-11g
    container_name: oracle11g
    ports:
      - "1521:1521"
      - "8080:8080"

  spring-docker:
    image: jsohee98/spring-docker
    build: ./spring-docker
    ports:
      - "8000:8000"

  vue-spring:
    image: jsohee98/vue-spring
    build: ./vue-spring
    ports:
      - "8081:8081"
